language: java
jdk: oraclejdk8

script:
- ./mvn clean package docker:build

sudo: required
 
services:
  - docker
  
after_success:
  - docker login -u lamt3 -p Tomokilam3
  - docker push lamt3/bazaar-restaurants-image
  
 