language: java
jdk: oraclejdk8
sudo: required

services:
  - docker

script:
- docker login -u lamt3 -p Tomokilam3
- mvn clean package docker:build


 

  
after_success:
  - docker push lamt3/bazaar-restaurants-image
  
 