version: '3'

services:
   vendors-app:
    image: bazaar-vendors-image
    ports:
    - "8082:8082"
   restaurants-app:
    image: bazaar-restaurants-image
    ports:
    - "8083:8083"
    links:
    - vendors-app 